/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/**
 * @fileoverview Utility for validating CEL conditions offline.
 */

export const VALID_CEL_CONTENT_TYPES = [
  'all_content',
  'body',
  'subject',
  'title',
  'suggestion',
  'access_levels',
  'destination_type',
  'destination_url',
  'source_url',
  'url',
  'url_category',
  'source_chrome_context',
  'all_headers',
  'envelope_from',
  'from_header',
  'sender_header',
  'to_header_recipients',
  'message_security_status',
  'file_size_in_bytes',
  'file_type',
  'drive_enterprise_metadata',
  'encryption_state',
]
export const VALID_CEL_METHODS = [
  'contains',
  'starts_with',
  'ends_with',
  'equals',
  'matches_dlp_detector',
  'matches_regex_detector',
  'matches_word_list',
  'matches_web_category',
]

export const VALID_WEB_CATEGORIES = [
  'ADULT',
  'ARTS_AND_ENTERTAINMENT',
  'AUTOS_AND_VEHICLES',
  'BEAUTY_AND_FITNESS',
  'BOOKS_AND_LITERATURE',
  'BUSINESS_AND_INDUSTRIAL',
  'COMPUTERS_AND_ELECTRONICS',
  'FINANCE',
  'FOOD_AND_DRINK',
  'GAMES',
  'HEALTH',
  'HOBBIES_AND_LEISURE',
  'HOME_AND_GARDEN',
  'INTERNET_AND_TELECOM',
  'JOBS_AND_EDUCATION',
  'LAW_AND_GOVERNMENT',
  'NEWS',
  'ONLINE_COMMUNITIES',
  'PEOPLE_AND_SOCIETY',
  'PETS_AND_ANIMALS',
  'REAL_ESTATE',
  'REFERENCE',
  'SCIENCE',
  'SENSITIVE_SUBJECTS',
  'SHOPPING',
  'SPORTS',
  'TRAVEL',
  'TRAVEL_AND_TRANSPORTATION',
  'GAMBLING',
  'ARTS_AND_ENTERTAINMENT__CELEBRITIES_AND_ENTERTAINMENT_',
  'ARTS_AND_ENTERTAINMENT__COMICS_AND_ANIMATION',
  'ARTS_AND_ENTERTAINMENT__ENTERTAINMENT_INDUSTRY',
  'ARTS_AND_ENTERTAINMENT__EVENTS_AND_LISTINGS',
  'ARTS_AND_ENTERTAINMENT__FUN_AND_TRIVIA',
  'ARTS_AND_ENTERTAINMENT__HUMOR',
  'ARTS_AND_ENTERTAINMENT__MOVIES',
  'ARTS_AND_ENTERTAINMENT__MUSIC_AND_AUDIO',
  'ARTS_AND_ENTERTAINMENT__OFFBEAT',
  'ARTS_AND_ENTERTAINMENT__ONLINE_MEDIA',
  'ARTS_AND_ENTERTAINMENT__PERFORMING_ARTS',
  'ARTS_AND_ENTERTAINMENT__TV_AND_VIDEO',
  'ARTS_AND_ENTERTAINMENT__VISUAL_ART_AND_DESIGN',
  'AUTOS_AND_VEHICLES__BICYCLES_AND_ACCESSORIES',
  'AUTOS_AND_VEHICLES__BOATS_AND_WATERCRAFT',
  'AUTOS_AND_VEHICLES__CAMPERS_AND_RVS',
  'AUTOS_AND_VEHICLES__CLASSIC_VEHICLES',
  'AUTOS_AND_VEHICLES__COMMERCIAL_VEHICLES',
  'AUTOS_AND_VEHICLES__CUSTOM_AND_PERFORMANCE_VEHICLES',
  'AUTOS_AND_VEHICLES__MOTOR_VEHICLES',
  'AUTOS_AND_VEHICLES__PERSONAL_AIRCRAFT',
  'AUTOS_AND_VEHICLES__VEHICLE_CODES_AND_DRIVING_LAWS',
  'AUTOS_AND_VEHICLES__VEHICLE_PARTS_AND_SERVICES',
  'AUTOS_AND_VEHICLES__VEHICLE_SHOPPING',
  'AUTOS_AND_VEHICLES__VEHICLE_SHOWS',
  'BEAUTY_AND_FITNESS__BEAUTY_PAGEANTS',
  'BEAUTY_AND_FITNESS__BEAUTY_SERVICES_AND_SPAS',
  'BEAUTY_AND_FITNESS__BODY_ART',
  'BEAUTY_AND_FITNESS__COSMETOLOGY_AND_BEAUTY_PROFESSIONALS',
  'BEAUTY_AND_FITNESS__FACE_AND_BODY_CARE',
  'BEAUTY_AND_FITNESS__FASHION_AND_STYLE',
  'BEAUTY_AND_FITNESS__FITNESS',
  'BEAUTY_AND_FITNESS__HAIR_CARE',
  'BEAUTY_AND_FITNESS__WEIGHT_LOSS',
  'BOOKS_AND_LITERATURE__AUDIOBOOKS',
  'BOOKS_AND_LITERATURE__BOOK_RETAILERS',
  'BOOKS_AND_LITERATURE__CHILDRENS_LITERATURE',
  'BOOKS_AND_LITERATURE__E_BOOKS',
  'BOOKS_AND_LITERATURE__FAN_FICTION',
  'BOOKS_AND_LITERATURE__LITERARY_CLASSICS',
  'BOOKS_AND_LITERATURE__MAGAZINES',
  'BOOKS_AND_LITERATURE__POETRY',
  'BOOKS_AND_LITERATURE__WRITERS_RESOURCES',
  'BUSINESS_AND_INDUSTRIAL__ADVERTISING_AND_MARKETING',
  'BUSINESS_AND_INDUSTRIAL__AEROSPACE_AND_DEFENSE',
  'BUSINESS_AND_INDUSTRIAL__AGRICULTURE_AND_FORESTRY',
  'BUSINESS_AND_INDUSTRIAL__AUTOMOTIVE_INDUSTRY',
  'BUSINESS_AND_INDUSTRIAL__BUSINESS_EDUCATION',
  'BUSINESS_AND_INDUSTRIAL__BUSINESS_FINANCE',
  'BUSINESS_AND_INDUSTRIAL__BUSINESS_OPERATIONS',
  'BUSINESS_AND_INDUSTRIAL__BUSINESS_SERVICES',
  'BUSINESS_AND_INDUSTRIAL__CHEMICALS_INDUSTRY',
  'BUSINESS_AND_INDUSTRIAL__CONSTRUCTION_AND_MAINTENANCE',
  'BUSINESS_AND_INDUSTRIAL__ENERGY_AND_UTILITIES',
  'BUSINESS_AND_INDUSTRIAL__HOSPITALITY_INDUSTRY',
  'BUSINESS_AND_INDUSTRIAL__INDUSTRIAL_MATERIALS_AND_EQUIPMENT',
  'BUSINESS_AND_INDUSTRIAL__MANUFACTURING',
  'BUSINESS_AND_INDUSTRIAL__METALS_AND_MINING',
  'BUSINESS_AND_INDUSTRIAL__PHARMACEUTICALS_AND_BIOTECH',
  'BUSINESS_AND_INDUSTRIAL__PRINTING_AND_PUBLISHING',
  'BUSINESS_AND_INDUSTRIAL__PROFESSIONAL_AND_TRADE_ASSOCIATIONS',
  'BUSINESS_AND_INDUSTRIAL__RETAIL_TRADE',
  'BUSINESS_AND_INDUSTRIAL__SHIPPING_AND_LOGISTICS',
  'BUSINESS_AND_INDUSTRIAL__SMALL_BUSINESS',
  'BUSINESS_AND_INDUSTRIAL__TEXTILES_AND_NONWOVENS',
  'FINANCE__ACCOUNTING_AND_AUDITING',
  'FINANCE__BANKING',
  'FINANCE__CREDIT_AND_LENDING',
  'FINANCE__CROWDFUNDING',
  'FINANCE__DIGITAL_CURRENCIES',
  'FINANCE__FINANCIAL_PLANNING_AND_MANAGEMENT',
  'FINANCE__GRANTS_SCHOLARSHIPS_AND_FINANCIAL_AID',
  'FINANCE__INSURANCE',
  'FINANCE__INVESTING',
  'FOOD_AND_DRINK__ALCOHOLIC_BEVERAGES',
  'FOOD_AND_DRINK__BEVERAGES',
  'FOOD_AND_DRINK__COOKING_AND_RECIPES',
  'FOOD_AND_DRINK__FOOD',
  'FOOD_AND_DRINK__FOOD_AND_GROCERY_DELIVERY',
  'FOOD_AND_DRINK__FOOD_AND_GROCERY_RETAILERS',
  'FOOD_AND_DRINK__RESTAURANTS',
  'GAMES__ARCADE_AND_COIN_OP_GAMES',
  'GAMES__BOARD_GAMES',
  'GAMES__CARD_GAMES',
  'GAMES__COMPUTER_AND_VIDEO_GAMES',
  'GAMES__DICE_GAMES',
  'GAMES__EDUCATIONAL_GAMES',
  'GAMES__FAMILY_ORIENTED_GAMES_AND_ACTIVITIES',
  'GAMES__GAMBLING',
  'GAMES__PARTY_GAMES',
  'GAMES__PUZZLES_AND_BRAINTEASERS',
  'GAMES__ROLEPLAYING_GAMES',
  'GAMES__TABLE_GAMES',
  'GAMES__TILE_GAMES',
  'GAMES__WORD_GAMES',
  'HEALTH__AGING_AND_GERIATRICS',
  'HEALTH__ALTERNATIVE_AND_NATURAL_MEDICINE',
  'HEALTH__HEALTH_CONDITIONS',
  'HEALTH__HEALTH_EDUCATION_AND_MEDICAL_TRAINING',
  'HEALTH__HEALTH_FOUNDATIONS_AND_MEDICAL_RESEARCH',
  'HEALTH__MEDICAL_DEVICES_AND_EQUIPMENT',
  'HEALTH__MEDICAL_FACILITIES_AND_SERVICES',
  'HEALTH__MEDICAL_LITERATURE_AND_RESOURCES',
  'HEALTH__MENS_HEALTH',
  'HEALTH__MENTAL_HEALTH',
  'HEALTH__NURSING',
  'HEALTH__NUTRITION',
  'HEALTH__ORAL_AND_DENTAL_CARE',
  'HEALTH__PEDIATRICS',
  'HEALTH__PHARMACY',
  'HEALTH__PUBLIC_HEALTH',
  'HEALTH__REPRODUCTIVE_HEALTH',
  'HEALTH__SUBSTANCE_ABUSE',
  'HEALTH__VISION_CARE',
  'HEALTH__WOMENS_HEALTH',
  'HOBBIES_AND_LEISURE__CLUBS_AND_ORGANIZATIONS',
  'HOBBIES_AND_LEISURE__CRAFTS',
  'HOBBIES_AND_LEISURE__MERIT_PRIZES_AND_CONTESTS',
  'HOBBIES_AND_LEISURE__OUTDOORS',
  'HOBBIES_AND_LEISURE__PAINTBALL',
  'HOBBIES_AND_LEISURE__RADIO_CONTROL_AND_MODELING',
  'HOBBIES_AND_LEISURE__RECREATIONAL_AVIATION',
  'HOBBIES_AND_LEISURE__SPECIAL_OCCASIONS',
  'HOBBIES_AND_LEISURE__SWEEPSTAKES_AND_PROMOTIONAL_GIVEAWAYS',
  'HOBBIES_AND_LEISURE__WATER_ACTIVITIES',
  'HOME_AND_GARDEN__BED_AND_BATH',
  'HOME_AND_GARDEN__DOMESTIC_SERVICES',
  'HOME_AND_GARDEN__HOME_AND_INTERIOR_DECOR',
  'HOME_AND_GARDEN__HOME_APPLIANCES',
  'HOME_AND_GARDEN__HOME_FURNISHINGS',
  'HOME_AND_GARDEN__HOME_IMPROVEMENT',
  'HOME_AND_GARDEN__HOME_SAFETY_AND_SECURITY',
  'HOME_AND_GARDEN__HOME_STORAGE_AND_SHELVING',
  'HOME_AND_GARDEN__HOME_SWIMMING_POOLS_SAUNAS_AND_SPAS',
  'HOME_AND_GARDEN__HOUSEHOLD_SUPPLIES',
  'HOME_AND_GARDEN__HVAC_AND_CLIMATE_CONTROL',
  'HOME_AND_GARDEN__KITCHEN_AND_DINING',
  'HOME_AND_GARDEN__LAUNDRY',
  'HOME_AND_GARDEN__PATIO_LAWN_AND_GARDEN',
  'HOME_AND_GARDEN__PEST_CONTROL',
  'INTERNET_AND_TECHNOLOGY__AFFILIATE_PROGRAMS',
  'INTERNET_AND_TECHNOLOGY__BUSINESS_AND_PRODUCTIVITY_SOFTWARE',
  'INTERNET_AND_TECHNOLOGY__CLOUD_STORAGE',
  'INTERNET_AND_TECHNOLOGY__COLLABORATION_AND_CONFERENCING_SOFTWARE',
  'INTERNET_AND_TECHNOLOGY__COMMUNICATIONS_EQUIPMENT',
  'INTERNET_AND_TECHNOLOGY__COMPUTER_HARDWARE',
  'INTERNET_AND_TECHNOLOGY__COMPUTER_SECURITY',
  'INTERNET_AND_TECHNOLOGY__CONSUMER_ELECTRONICS',
  'INTERNET_AND_TECHNOLOGY__CONTENT_MANAGEMENT',
  'INTERNET_AND_TECHNOLOGY__EDUCATIONAL_SOFTWARE',
  'INTERNET_AND_TECHNOLOGY__ELECTRONICS_AND_ELECTRICAL',
  'INTERNET_AND_TECHNOLOGY__ELECTRONIC_SPAM',
  'INTERNET_AND_TECHNOLOGY__EMAIL',
  'INTERNET_AND_TECHNOLOGY__EMAIL_AND_MESSAGING',
  'INTERNET_AND_TECHNOLOGY__ENTERPRISE_TECHNOLOGY',
  'INTERNET_AND_TECHNOLOGY__FREEWARE_AND_SHAREWARE',
  'INTERNET_AND_TECHNOLOGY__GENERATIVE_AI',
  'INTERNET_AND_TECHNOLOGY__HACKING_AND_CRACKING',
  'INTERNET_AND_TECHNOLOGY__MOBILE_AND_WIRELESS',
  'INTERNET_AND_TECHNOLOGY__NETWORKING',
  'INTERNET_AND_TECHNOLOGY__OPEN_SOURCE',
  'INTERNET_AND_TECHNOLOGY__PROGRAMMING',
  'INTERNET_AND_TECHNOLOGY__PROXYING_AND_FILTERING',
  'INTERNET_AND_TECHNOLOGY__SEARCH_ENGINE_OPTIMIZATION_AND_MARKETING',
  'INTERNET_AND_TECHNOLOGY__SEARCH_ENGINES',
  'INTERNET_AND_TECHNOLOGY__SERVICE_PROVIDERS',
  'INTERNET_AND_TECHNOLOGY__SOFTWARE',
  'INTERNET_AND_TECHNOLOGY__TELECONFERENCING',
  'INTERNET_AND_TECHNOLOGY__TEXT_AND_INSTANT_MESSAGING',
  'INTERNET_AND_TECHNOLOGY__VOICE_AND_VIDEO_CHAT',
  'INTERNET_AND_TECHNOLOGY__VPN_AND_REMOTE_ACCESS',
  'INTERNET_AND_TECHNOLOGY__WEB_APPS_AND_ONLINE_TOOLS',
  'INTERNET_AND_TECHNOLOGY__WEB_DESIGN_AND_DEVELOPMENT',
  'INTERNET_AND_TECHNOLOGY__WEB_HOSTING_AND_DOMAIN_REGISTRATION',
  'INTERNET_AND_TECHNOLOGY__WEB_PORTALS',
  'INTERNET_AND_TECHNOLOGY__WEB_STATS_AND_ANALYTICS',
  'JOBS_AND_EDUCATION__EDUCATION',
  'JOBS_AND_EDUCATION__INTERNSHIPS',
  'JOBS_AND_EDUCATION__JOBS',
  'LAW_AND_GOVERNMENT__GOVERNMENT',
  'LAW_AND_GOVERNMENT__LEGAL',
  'LAW_AND_GOVERNMENT__MILITARY',
  'LAW_AND_GOVERNMENT__PUBLIC_SAFETY',
  'LAW_AND_GOVERNMENT__SOCIAL_SERVICES',
  'NEWS__BROADCAST_AND_NETWORK_NEWS',
  'NEWS__BUSINESS_NEWS',
  'NEWS__GOSSIP_AND_TABLOID_NEWS',
  'NEWS__HEALTH_NEWS',
  'NEWS__JOURNALISM_AND_NEWS_INDUSTRY',
  'NEWS__LOCAL_NEWS',
  'NEWS__NEWSPAPERS',
  'NEWS__POLITICS',
  'NEWS__SPORTS_NEWS',
  'NEWS__TECHNOLOGY_NEWS',
  'NEWS__WEATHER',
  'NEWS__WORLD_NEWS',
  'ONLINE_COMMUNITIES__BLOGGING_RESOURCES_AND_SERVICES',
  'ONLINE_COMMUNITIES__DATING_AND_PERSONALS',
  'ONLINE_COMMUNITIES__FEED_AGGREGATION_AND_SOCIAL_BOOKMARKING',
  'ONLINE_COMMUNITIES__FILE_SHARING_AND_HOSTING',
  'ONLINE_COMMUNITIES__FORUM_AND_CHAT_PROVIDERS',
  'ONLINE_COMMUNITIES__ONLINE_GOODIES',
  'ONLINE_COMMUNITIES__ONLINE_JOURNALS_AND_PERSONAL_SITES',
  'ONLINE_COMMUNITIES__PHOTO_AND_VIDEO_SHARING',
  'ONLINE_COMMUNITIES__SOCIAL_NETWORKS',
  'ONLINE_COMMUNITIES__VIRTUAL_WORLDS',
  'PEOPLE_AND_SOCIETY__DISABLED_AND_SPECIAL_NEEDS',
  'PEOPLE_AND_SOCIETY__ETHNIC_AND_IDENTITY_GROUPS',
  'PEOPLE_AND_SOCIETY__FAMILY_AND_RELATIONSHIPS',
  'PEOPLE_AND_SOCIETY__KIDS_AND_TEENS',
  'PEOPLE_AND_SOCIETY__RELIGION_AND_BELIEF',
  'PEOPLE_AND_SOCIETY__SELF_HELP_AND_MOTIVATIONAL',
  'PEOPLE_AND_SOCIETY__SENIORS_AND_RETIREMENT',
  'PEOPLE_AND_SOCIETY__SOCIAL_ISSUES_AND_ADVOCACY',
  'PEOPLE_AND_SOCIETY__SOCIAL_SCIENCES',
  'PEOPLE_AND_SOCIETY__SUBCULTURES_AND_NICHE_INTERESTS',
  'PETS_AND_ANIMALS__ANIMAL_PRODUCTS_AND_SERVICES',
  'PETS_AND_ANIMALS__PETS',
  'PETS_AND_ANIMALS__WILDLIFE',
  'REAL_ESTATE__PROPERTY_DEVELOPMENT',
  'REAL_ESTATE__REAL_ESTATE_LISTINGS',
  'REAL_ESTATE__REAL_ESTATE_SERVICES',
  'REFERENCE__DIRECTORIES_AND_LISTINGS',
  'REFERENCE__GENERAL_REFERENCE',
  'REFERENCE__GEOGRAPHIC_REFERENCE',
  'REFERENCE__HUMANITIES',
  'REFERENCE__LANGUAGE_RESOURCES',
  'REFERENCE__LIBRARIES_AND_MUSEUMS',
  'REFERENCE__TECHNICAL_REFERENCE',
  'SCIENCE__ASTRONOMY',
  'SCIENCE__BIOLOGICAL_SCIENCES',
  'SCIENCE__CHEMISTRY',
  'SCIENCE__COMPUTER_SCIENCE',
  'SCIENCE__EARTH_SCIENCES',
  'SCIENCE__ECOLOGY_AND_ENVIRONMENT',
  'SCIENCE__ENGINEERING_AND_TECHNOLOGY',
  'SCIENCE__MATHEMATICS',
  'SCIENCE__PHYSICS',
  'SCIENCE__SCIENTIFIC_EQUIPMENT',
  'SCIENCE__SCIENTIFIC_INSTITUTIONS',
  'SENSITIVE_SUBJECTS__ACCIDENTS_AND_DISASTERS',
  'SENSITIVE_SUBJECTS__DEATH_AND_TRAGEDY',
  'SENSITIVE_SUBJECTS__FIREARMS_AND_WEAPONS',
  'SENSITIVE_SUBJECTS__MISSING_PERSONS_AND_ABDUCTIONS',
  'SENSITIVE_SUBJECTS__RECREATIONAL_DRUGS',
  'SENSITIVE_SUBJECTS__SELF_HARM',
  'SENSITIVE_SUBJECTS__VIOLENCE_AND_ABUSE',
  'SENSITIVE_SUBJECTS__WAR_AND_CONFLICT',
  'SHOPPING__ANTIQUES_AND_COLLECTIBLES',
  'SHOPPING__APPAREL',
  'SHOPPING__AUCTIONS',
  'SHOPPING__CLASSIFIEDS',
  'SHOPPING__CONSUMER_RESOURCES',
  'SHOPPING__DISCOUNT_AND_OUTLET_STORES',
  'SHOPPING__ENTERTAINMENT_MEDIA',
  'SHOPPING__GIFTS_AND_SPECIAL_EVENT_ITEMS',
  'SHOPPING__GREEN_AND_ECO_FRIENDLY_SHOPPING',
  'SHOPPING__LUXURY_GOODS',
  'SHOPPING__MASS_MERCHANTS_AND_DEPARTMENT_STORES',
  'SHOPPING__PHOTO_AND_VIDEO_SERVICES',
  'SHOPPING__SHOPPING_PORTALS',
  'SHOPPING__SWAP_MEETS_AND_OUTDOOR_MARKETS',
  'SHOPPING__TOBACCO_AND_VAPING_PRODUCTS',
  'SHOPPING__TOYS',
  'SHOPPING__WHOLESALERS_AND_LIQUIDATORS',
  'SPORTS__ANIMAL_SPORTS',
  'SPORTS__COLLEGE_SPORTS',
  'SPORTS__COMBAT_SPORTS',
  'SPORTS__EXTREME_SPORTS',
  'SPORTS__FANTASY_SPORTS',
  'SPORTS__INDIVIDUAL_SPORTS',
  'SPORTS__INTERNATIONAL_SPORTS_COMPETITIONS',
  'SPORTS__MOTOR_SPORTS',
  'SPORTS__SPORTING_GOODS',
  'SPORTS__SPORTS_COACHING_AND_TRAINING',
  'SPORTS__SPORT_SCORES_AND_STATISTICS',
  'SPORTS__SPORTS_FAN_GEAR_AND_APPAREL',
  'SPORTS__TEAM_SPORTS',
  'SPORTS__WATER_SPORTS',
  'SPORTS__WINTER_SPORTS',
  'TRAVEL_AND_TRANSPORTATION__HOTELS_AND_ACCOMMODATIONS',
  'TRAVEL_AND_TRANSPORTATION__LUGGAGE_AND_TRAVEL_ACCESSORIES',
  'TRAVEL_AND_TRANSPORTATION__SPECIALTY_TRAVEL',
  'TRAVEL_AND_TRANSPORTATION__TOURIST_DESTINATIONS',
  'TRAVEL_AND_TRANSPORTATION__TRANSPORTATION',
  'TRAVEL_AND_TRANSPORTATION__TRAVEL_AGENCIES_AND_SERVICES',
  'TRAVEL_AND_TRANSPORTATION__TRAVEL_GUIDES_AND_TRAVELOGUES',
]

/**
 * Basic offline CEL validator for DLP conditions.
 * @param {string} condition - The CEL condition string
 * @param {string[]} triggers - Optional list of triggers
 * @returns {{isValid: boolean, errors: string[]}} Validation result
 */
export function validateCelCondition(condition, triggers = []) {
  const errors = []

  if (!condition || condition.trim() === '') {
    return { isValid: false, errors: ['Condition cannot be empty.'] }
  }

  // Check balanced parentheses
  let openParen = 0
  for (const char of condition) {
    if (char === '(') {
      openParen++
    }
    if (char === ')') {
      openParen--
    }
    if (openParen < 0) {
      errors.push('Unbalanced parentheses: too many closing parentheses.')
      break
    }
  }
  if (openParen > 0) {
    errors.push('Unbalanced parentheses: missing closing parentheses.')
  }

  // Strip string literals to avoid false positives in regex checks
  let strippedCondition = condition
  try {
    strippedCondition = condition.replace(/("[^"\\]*(?:\\.[^"\\]*)*"|'[^'\\]*(?:\\.[^'\\]*)*')/g, '""')
  } catch (e) {
    // Ignore regex errors
  }

  // Check if methods are valid
  const methodRegex = /\.([a-zA-Z0-9_]+)\(/g
  let match
  while ((match = methodRegex.exec(strippedCondition)) !== null) {
    const method = match[1]
    if (!VALID_CEL_METHODS.includes(method)) {
      errors.push(
        `Invalid function/method called: '${method}'. Supported functions are: ${VALID_CEL_METHODS.join(', ')}.`,
      )
    }
  }

  // Make sure at least one valid content type is used
  const hasValidContentType = VALID_CEL_CONTENT_TYPES.some(type => strippedCondition.includes(`${type}.`))
  if (!hasValidContentType) {
    errors.push(
      `Condition does not appear to use a valid content type. Must use one of: ${VALID_CEL_CONTENT_TYPES.join(', ')} followed by a dot.`,
    )
  }

  // Validate categories inside matches_web_category
  const webCategoryRegex = /\.matches_web_category\(\s*['"]([^'"]+)['"]\s*\)/g
  let catMatch
  while ((catMatch = webCategoryRegex.exec(condition)) !== null) {
    const category = catMatch[1]
    if (!VALID_WEB_CATEGORIES.includes(category)) {
      errors.push(
        `'${category}' is not a recognized web category. Supported categories are: ${VALID_WEB_CATEGORIES.join(', ')}.`,
      )
    }
  }

  // Hard fail if url.matches_web_category is used instead of url_category
  if (condition.includes('url.matches_web_category')) {
    errors.push(
      "The 'matches_web_category' function must be called on 'url_category', not 'url' (i.e. 'url_category.matches_web_category(...)').",
    )
  }

  // Cross-reference triggers (basic checks)
  if (triggers.length > 0) {
    if (condition.includes('.matches_web_category') && !triggers.includes('NAVIGATION')) {
      errors.push(
        `The 'matches_web_category' function is typically only supported with the 'NAVIGATION' trigger. Current triggers: ${triggers.join(', ')}.`,
      )
    }

    // Trigger compatibility checks for URL attributes
    if (triggers.includes('NAVIGATION') || triggers.includes('FILE_DOWNLOAD')) {
      if (condition.includes('source_url.') || condition.includes('destination_url.')) {
        errors.push(
          `Trigger '${triggers.find(t => t === 'NAVIGATION' || t === 'FILE_DOWNLOAD')}' does not support 'source_url' or 'destination_url'. Use 'url' instead.`,
        )
      }
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
  }
}
