/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/**
 * @file Compiles all markdown documents and dynamic docs into a single static JS file
 * to eliminate runtime filesystem reads.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import matter from 'gray-matter'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const ROOT = path.resolve(__dirname, '..')
const KNOWLEDGE_DIR = path.join(ROOT, 'lib/knowledge')
const SYSTEM_PROMPT_PATH = path.join(ROOT, 'prompts/system-prompt.md')
const CAPABILITIES_PATH = path.join(KNOWLEDGE_DIR, '0-agent-capabilities.md')
const ADDENDUM_PATH = path.join(KNOWLEDGE_DIR, '98-agent-knowledge-addendum.md')
const GUIDELINES_PATH = path.join(KNOWLEDGE_DIR, '15-rule-quality-guidelines.md')
const OUTPUT_PATH = path.join(KNOWLEDGE_DIR, 'compiled_docs.js')

const NON_PUBLIC_KNOWLEDGE_FILES = new Set(['README.md', '0-agent-capabilities.md'])

/**
 * Scans the knowledge directory and returns static markdown entries.
 * @param {string} dir - The directory to scan.
 * @returns {Array<object>} The list of scanned document objects.
 */
function scanStaticDocs(dir) {
  const entries = []
  const files = fs.readdirSync(dir)
  files.sort((a, b) => {
    const numA = parseInt(a.split('-')[0])
    const numB = parseInt(b.split('-')[0])
    if (!isNaN(numA) && !isNaN(numB)) {
      return numA - numB
    }
    return a.localeCompare(b)
  })
  for (const file of files) {
    if (!file.endsWith('.md') || NON_PUBLIC_KNOWLEDGE_FILES.has(file)) {
      continue
    }
    const filePath = path.join(dir, file)
    const fileContent = fs.readFileSync(filePath, 'utf-8')
    const { data: metadata, content } = matter(fileContent)
    entries.push({
      file,
      filename: file.replace(/\.md$/, ''),
      metadata,
      content,
    })
  }
  return entries
}

/**
 * Discovers and loads dynamic documentation modules.
 * @param {string} dir - The directory to scan for dynamic docs.
 * @returns {Promise<Array<object>>} A promise that resolves to the list of loaded docs.
 */
async function loadDynamicDocs(dir) {
  const docs = []
  const files = fs.readdirSync(dir)
  for (const file of files) {
    if (file.endsWith('.doc.js') && file !== 'compiled_docs.js') {
      const filePath = path.join(dir, file)
      const module = await import(pathToFileURL(filePath).href)
      if (module.doc) {
        docs.push({
          ...module.doc,
          filename: file.replace('.doc.js', ''),
          kind: module.doc.kind || 'curated',
        })
      }
    }
  }
  return docs
}

/**
 * Main execution function to compile documents.
 * @returns {Promise<void>}
 */
async function main() {
  console.log('Compiling documents...')

  const systemPrompt = fs.readFileSync(SYSTEM_PROMPT_PATH, 'utf8')
  const capabilities = fs.readFileSync(CAPABILITIES_PATH, 'utf8')
  const addendum = fs.readFileSync(ADDENDUM_PATH, 'utf8')
  const ruleQualityGuidelines = fs.readFileSync(GUIDELINES_PATH, 'utf8')

  const staticDocs = scanStaticDocs(KNOWLEDGE_DIR)
  const dynamicDocs = await loadDynamicDocs(KNOWLEDGE_DIR)

  const content = `/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// @ts-nocheck
// Auto-generated by tools/compile-docs.js. Do not edit.

export const systemPrompt = ${JSON.stringify(systemPrompt)}

export const capabilities = ${JSON.stringify(capabilities)}

export const addendum = ${JSON.stringify(addendum)}

export const ruleQualityGuidelines = ${JSON.stringify(ruleQualityGuidelines)}

export const staticDocs = ${JSON.stringify(staticDocs, null, 2)}

export const dynamicDocs = ${JSON.stringify(dynamicDocs, null, 2)}
`

  fs.writeFileSync(OUTPUT_PATH, content, 'utf8')
  console.log(`Compiled documents written to ${OUTPUT_PATH}`)
}

main().catch(err => {
  console.error('Failed to compile documents:', err)
  throw err
})
